app/project/urls.py
from django.conf.urls.defaults import *
from utils import *

urlpatterns = patterns('',
    # Task
    url(r'^debug', 'project.views.debug'),
    url(r'^$', 'project.views.front_page', name="front_page"),
    url(r'^my-dashboard/$', 'project.views.my_dashboard', name="my-dashboard-view"),
    url(r'^user-dashboard/(?P<user_id>\d+)/$', 'project.views.user_dashboard', name="user-dashboard-view"),
    url(r'^show_task/$', 'project.views.show_task', name="show-task"),
    url(r'^action_task/$', 'project.views.action_task', name="action_task"),
    url(r'^task/quick_edit/$', 'project.views.quick_edit', name="quick_edit"),
    url(r'^task/delete_task/$', 'project.views.delete_task', name="delete_task"),
    url(r'task/file_upload/$', 'project.views.upload_file', name='uploadify_upload'),
    url(r'task/file_delete/$', 'project.views.delete_file', name='uploadify_delete'),
    url(r'task/print/(?P<object_id>\d+)/$', 'project.views.print_page', name="print_page"),
    url(r'^tasks-bulk-action/$', 'project.views.tasks_bulk_action', name="tasks_bulk_action"),
    
    # History Uri
    url(r'^my-history/$', 'project.views.my_history', name="my-history-view"),
    url(r'^history/(?P<user_id>\d+)/$', 'project.views.user_history', name="user-history-view"),
    url(r'^save_attention_time/$', 'project.views.save_history_time'),
    url(r'^my-history_standalone/$', 'project.views.my_history', {"is_standalone": 1}, name="my-history_standalone" ),
    url(r'^history_standalone/$', 'project.views.user_history', {"is_standalone": 1}, name="user-history_standalone" ),
    url(r'^history/history_list/$', 'project.views.history_list', name="history_list"),
    url(r'^history/history_task_view/$', 'project.views.history_task_view', name="history_task_view"),
    url(r'^history-object/(?P<hash_task>\d+)/$', 'project.views.history_object', name="history_object"),
    
    # Reports Url
    url(r'^reports/$', 'project.views.reports', name="reports-view"),
    url(r'^reports/stat/$', 'project.views.report_stat', name="report_stat"),
    url(r'^reports/stat/open_tasks/$', 'project.views.report_stat_opened', name="report-open-tasks"),
    url(r'^reports/stat/employees/$', 'project.views.report_employees', name="report-employees"),
    url(r'^reports/stat/print_open_tasks/$', 'project.views.report_print_open_tasks', name="report-print-open-tasks"),
    
    # Query
    #url(r'query/0/$', 'project.views.query_tab_0', name="query_tab_0"),
    url(r'query/canceled_tasks/$', 'project.views.query_canceled_tasks', name="query_canceled_tasks"),
    url(r'query/closing_tasks/$', 'project.views.query_closing_tasks', name="query_closing_tasks"),
    url(r'query/completion_date_changes/$', 'project.views.query_completion_date_changes', name="query_completion_date_changes"),
    url(r'query/deleted_tasks/$', 'project.views.query_deleted_tasks', name="query_deleted_tasks"),
    url(r'query/load_distribution/$', 'project.views.query_load_distribution', name="query_load_distribution"),
	url(r'query/load_distribution/(\d+)$', 'project.views.query_load_distribution', name="query_load_distribution"),
    url(r'query/most_least_variable_task/$', 'project.views.query_most_least_variable_task', name="query_most_least_variable_task"),
    url(r'query/overdue_tasks/$', 'project.views.query_overdue_tasks', name="query_overdue_tasks"),
    url(r'query/overdue_tasks/view/$', 'project.views.query_overdue_tasks_view', name="query_overdue_tasks_view"),
    url(r'query/planning_errors/$', 'project.views.query_planning_errors', name="query_planning_errors"),
    url(r'query/start_date_changes/$', 'project.views.query_start_date_changes', name="query_start_date_changes"),
    url(r'query/task_count_dynamics/$', 'project.views.query_task_count_dynamics', name="query_task_count_dynamics"),
    url(r'query/tasks_delegation_level/$', 'project.views.query_tasks_delegation_level', name="query_tasks_delegation_level"),
    url(r'query/tasks_status_review/$', 'project.views.query_tasks_status_review', name="query_tasks_status_review"),
    url(r'query/tasks_value/$', 'project.views.query_tasks_value', name="query_tasks_value"),
	url(r'query/tasks_value/(\d+)$', 'project.views.query_tasks_value', name="query_tasks_value"),
    url(r'query/attention_distribution/$', 'project.views.query_attention_distribution', name="query_attention_distribution"),
    url(r'query/average_control_term/$', 'project.views.query_average_control_term', name="query_average_control_term"),
    url(r'query/query_task_complexity_distribution/$', 'project.views.query_task_complexity_distribution', name="query_task_complexity_distribution"),
    url(r'query/query_change_task_completion_terms/$', 'project.views.query_change_task_completion_terms', name="query_change_task_completion_terms"),
    url(r'query/low_active_employees/$', 'project.views.query_low_active_employees', name="query_low_active_employees"),
    url(r'query/query_tasks_changed_statement/$', 'project.views.query_tasks_changed_statement', name="query_tasks_changed_statement"),

    url(r'query/attention_distribution_time/$', 'project.views.query_attention_distribution_time', name="query_attention_distribution_time"),
    url(r'query/attention_distribution_time2/$', 'project.views.query_attention_distribution_time2', name="query_attention_distribution_time2"),
    url(r'query/manager_tasks_distribution/$', 'project.views.query_manager_tasks_distribution', name="query_manager_tasks_distribution"),
    url(r'query/manager_tasks_control_percent/$', 'project.views.query_manager_tasks_control_percent', name="query_manager_tasks_control_percent"),
    url(r'query/query_task_fulfillment_report/$', 'project.views.query_task_fulfillment_report', name="query_task_fulfillment_report"),

    url(r'query/subordinate_tasks_distribution/$', 'project.views.query_subordinate_tasks_distribution', name="query_subordinate_tasks_distribution"),
    url(r'query/maximal_chain/$', 'project.views.query_maximal_chain', name="query_maximal_chain"),
    url(r'query/timeliness/$', 'project.views.query_timeliness', name="query_timeliness"),
    url(r'query/timeliness/(\w+)$', 'project.views.query_timeliness', name="query_timeliness"),
    url(r'query/title_or_text_changed_tasks/$', 'project.views.title_or_text_changed_tasks', name="title_or_text_changed_tasks"),


    #Graph
    url(r'^graph/$', 'project.views.graph', name="graph"),
    url(r'^graph/1/$', 'project.views.graph_1', name="graph_1"),
    url(r'^graph/2/$', 'project.views.graph_2', name="graph_2"),
    url(r'^graph/subordinate_tasks_distribution/$', 'project.views.graph_subordinate_tasks_distribution', name="graph_subordinate_tasks_distribution"),
    
    # Search
    url(r'^search/$', 'project.views.search', name="project_search"),


)

if is_test():
    urlpatterns += (
        # Query
        url(r'query/13/$', 'project.views.query_tab_13', name="query_tab_13"),

        #Graph
        url(r'^graph/3/$', 'project.views.graph_3', name="graph_3"),
        url(r'^graph/4/$', 'project.views.graph_4', name="graph_4"),
        #url(r'^graph/5/$', 'project.views.graph_5', name="graph_5"),
    )

lib/uploadify/urls.py
from django.conf.urls.defaults import *
from uploadify.views import *

urlpatterns = patterns('',
    url(r'upload/$', upload, name='uploadify_upload'),
)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

# Устанавливаем свои вьюхи для ошибок 
handler403 = 'views.error403' # доступ запрещен
handler404 = 'views.error404' # страница не существует

urlpatterns = patterns('',
                       (r'^uploadify/', include('uploadify.urls')),
                       (r'^', include('project.urls')),
                       url('', include('registration.urls')),
                       # Calendar
                       url(r'^calendar/', include('django_bootstrap_calendar.urls')),
                       (r'^grappelli/', include('grappelli.urls')),
                       (r'^', include('accounts.urls')),
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                           'document_root': settings.STATIC_ROOT,
                       }),
)

# if settings.DEBUG:
    # urlpatterns += patterns('',
    #                         url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
    #                             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    # ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
                            url(r'^rosetta/', include('rosetta.urls')),
    )

app/helper/forms.py
# -*- coding: utf-8 -*-
from datetime import datetime, timedelta, time
from dateutil.relativedelta import relativedelta
from django import forms
import constants

class PeriodFilters(forms.Form):
    '''
    Форма позволяющая выбрать диапазон дат.
    Можно выбирать как предустановленный диапазон (сегодня, последняя неделя ... ),
    так и произвольный.
    '''
    class Media():
        js = ('js/filter_period.js',)

    EMPTY_PERIOD_CHOICE = ('', u'- Выбрать период -')
    period = forms.ChoiceField(
        choices  = (EMPTY_PERIOD_CHOICE,) + constants.PERIOD_CHOICES,
        label    = u'Период',
        required = False,
    )
    start = forms.DateField(
        label    = u'от',
        required = False,
    )
    end = forms.DateField(
        label    = u'до',
        required = False,
    )

    def __init__(self, *args, **kwargs):
        super(PeriodFilters, self).__init__(*args, **kwargs)
        self.fields['period'].widget.attrs = {
            'class': 'form-filters__period',
        }
        self.fields['start'].widget.attrs = {
            'class': 'form-filters__start-date',
        }
        self.fields['end'].widget.attrs = {
            'class': 'form-filters__end-date',
        }

    def clean(self):
        values = super(PeriodFilters, self).clean()
        self.define_date_period()
        return values

    def define_date_period(self):
        values = self.cleaned_data
        today = datetime.today()
        today_start = datetime.combine(today, time.min)
        today_end   = datetime.combine(today, time.max)
        mega_small_date = datetime(1900, 1, 1)
        mega_big_date = datetime(2900, 1, 1)

        if not values['period']:
            # start = today_start
            # end   = today_end
            values['period'] = 'all_time'

        if values['period'] == 'custom':
            start = values['start']
            end   = values['end']
        else:
            end = today_end
            if values['period'] == 'today':
                start = end.replace(hour = 0, minute = 1)
            elif values['period'] == 'last_week':
                start = end + relativedelta(days = -7)
            elif values['period'] == 'last_month':
                start = end + relativedelta(months = -1)
            elif values['period'] == 'last_quart':
                start = end + relativedelta(months = -3)
            elif values['period'] == 'last_year':
                start = end + relativedelta(years = -1)
            elif values['period'] == 'cur_month':
                start = end.replace(day = 1)
            elif values['period'] == 'all_time':
                start = mega_small_date
                end = mega_big_date

        self.start = start
        self.end   = end

app/project/templates/project/query/tasks_changed_statement/base.html
{% extends "project/base.html" %}
{% load i18n %}
{% block content %}
    {% include "project/common/tablesorter.html" %}
    <div class="container-fluid">
        <div class="page-header">
            <h2>
                {% blocktrans with date_to=date_to|date:'d E Y' date_from=date_from|date:'d E Y' %}
                    Процент поручений, по которым вносились изменения в формулировку за период с {{ date_from }} по {{ date_to }}
                {% endblocktrans %}
            </h2>
            <hr/>
            {% if filter_form %}
                <div class="filters__item users-stat-filters__period">
                    <form action="" method="get">
                        {{ filter_form.media }}
                        {{ filter_form.as_p }}
                    </form>
                    <script type="text/javascript">
                        $(function() {
                            $('#id_period, #id_display_type, #id_start, #id_end, #id_change_initiator, #id_user').change(function() {
                                var period = $('#id_period').val();
                                if(period == 'custom') {
                                    if($('#id_start').val() && $('#id_end').val()) {
                                        $(this).parents('form:first').submit();
                                    }
                                }
                                else {
                                    $(this).parents('form:first').submit();
                                }
                            });
                        });
                    </script>
                </div>
            {% endif %}
        </div>
        {% block query_results %}
        {% endblock %}
    </div>
{% endblock %}

app/project/templates/project/query/tasks_changed_statement/table_departments.html
{% extends "project/query/tasks_changed_statement/base.html" %}
{% load i18n %}
{% block query_results %}
    <table class="table table-striped tablesorter" id="main-table">
        <thead>
        <tr>
            <th>{% trans 'Наименование подразделения' %}</th>
            <th>{% trans 'Поручения, в которых менялась формулировка по инициативе исполнителя' %} (%)</th>
            <th>{% trans 'Поручения, в которых менялась формулировка по инициативе поручающего' %} (%)</th>
            <th>{% trans 'Общее кол-во поручений (шт) в управлении' %}</th>
        </tr>
        </thead>
        <tbody>
        {% for department in departments %}
            <tr>
                <td>{{ department.title }}</td>
                <td>{{ department.changed_by_performer_percent }}%</td>
                <td>{{ department.changed_by_manager_percent }}%</td>
                <td>{{ department.tasks_total }} {% trans 'шт.' %}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th>{% trans 'Всего' %}</th>
            <th>{{ total.changed_by_performer_percent }}%</th>
            <th>{{ total.changed_by_manager_percent }}%</th>
            <th>{{ total.tasks_count }} {% trans 'шт.' %}</th>
        </tr>
        </tfoot>
    </table>
{% endblock %}

app/project/templates/project/query/tasks_changed_statement/table_users.html
{% extends "project/query/tasks_changed_statement/base.html" %}
{% load i18n %}
{% block query_results %}
    <table class="table table-striped tablesorter" id="main-table">
        <thead>
        <tr>
            {% if change_initiator == 'manager' %}
                <th>{% trans 'ФИО исполнителя' %}</th>
                <th>{% trans 'Должность исполнителя' %}</th>
            {% else %}
                <th>{% trans 'ФИО поручающего' %}</th>
                <th>{% trans 'Должность поручающего' %}</th>
            {% endif %}
            <th colspan="2">{% trans 'Наименование поручения' %}</th>

        </tr>
        </thead>
        <tbody>
        {% for row in changed_tasks %}
            <tr>
                {% if change_initiator == 'manager' %}
                    <td>{{ row.author_task.get_profile.get_names }}</td>
                    <td>{{ row.author_task.get_profile.job|default:"------" }} <br/>
                        <small><b>{{ row.author_task.get_profile.tree }}</b></small></td>
                {% else %}
                    <td>{{ row.author.get_profile.get_names }}</td>
                    <td>{{ row.author.get_profile.job|default:"------" }} <br/>
                        <small><b>{{ row.author.get_profile.tree }}</b></small></td>
                {% endif %}
                <td colspan="2">{{ row.title }}</td>
            </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <th>{% trans 'Поручения, в которых менялась формулировка' %}</th>
        <th>{{ changed_statement_tasks_percent }}%</th>
        <th>{% trans 'Общее кол-во поручений (шт)' %}</th>
        <th>{{ tasks_total }}</th>
        </tfoot>
    </table>
{% endblock %}